actors:
  a2c:
    image_url: /images/actors/a2c.jpg
    name: a2c
    url: https://twitter.com/atusi
  namaiki:
    image_url: /images/actors/shiromai.jpg
    name: shiromai
    url: https://twitter.com/namaikicastle
author: a2c
description: Drone News/Tips/Race/Tool/etc
description_long: ドローンに関するエトセトラ
email: a2cgle@gmail.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics: UA-135021159-1
hashtag: powerloopfm
itunes_podcast_url:
keywords: drone,game,race,tool,tip
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: PowerLoop fm
url: https://powerloop.tokyo/
theme: jekyll-theme-midnight
